name: Sync Labels

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: actions-ecosystem/action-sync-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: .github/labels.yml
